spring:
  application:
    name: HRBank-team1

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hrbank
    username: hrbank_user
    password: hrbank1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

# Logging
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

#  h2:
#    console:
#      enabled: true

schedule:
  backup-cron: "0 0 0/1 * * *"

hrBank:
  repository:
    file-directory: files
